version: 0.2
env:
  shell: bash
  variables:
    ENV: "test"
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo setting extra env variables
      - . ./aws_buildspecs/build_extras.sh
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_GIT_MESSAGE
      - echo $CODEBUILD_GIT_BRANCH
      - echo $CODEBUILD_PULL_REQUEST
      - |
        [ "$BUILD_APP1" = "true" ] && echo "Build App1"
      - |
        [ "$BUILD_APP2" = "true" ] &&  echo "Build App2"
      - |
        [ "$BUILD_APP3" = "true" ] && echo "Build App3"
     