version: 0.2
env:
  shell: bash
  variables:
    ENV: "test"
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo setting extra env variables
      - . ./aws_buildspecs/build_extras.sh "App1 App2 App3"
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_GIT_MESSAGE
      - echo $CODEBUILD_GIT_BRANCH
      - echo $CODEBUILD_PULL_REQUEST
      - echo $BUILD_APPS
      - for app in $(echo $BUILD_APPS | sed "s/,/ /g");
          do
            echo "Build app $app";
          done
     